spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/joeldemo?characterEncoding=utf-8&serverTimezone=Asia/Taipei
      username: root
      password: springboot
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      jdbc-url: jdbc:mysql://localhost:3306/joeldemo2?characterEncoding=utf-8&serverTimezone=Asia/Taipei
      username: root
      password: springboot
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    enabled: true                     #啟用thymeleaf檢視
    content-type: text/html           #設定Content-Type值
    check-template-location: true     # 檢查模板是否存在，然後再呈現
    prefix: classpath:/templates/     # 設定去templates資料夾找html檔案
    suffix: .html                     # 構建字尾
mybatis:
  mapper-locations: classpath:/resources/mapper/**/*.xml
  type-aliases-package: com.example.demo.dao
server:
  port: 8081
logging:
  config: classpath:log4j2.yml
  level:
    root: INFO 
    com.example.demo.dao.*: DEBUG
    org.springframework: ERROR
  file:
    max-size: 10MB
    max-history: 2
 


